/*
 * @Description:
 * @Version: 0.0.0
 * @Autor: wenqiang
 * @Date: 2021-07-02 16:44:14
 * @LastEditors: Please set LastEditors
 * @LastEditTime: 2021-07-22 17:35:56
 */
// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElMenuItem: typeof import('element-plus/es/el-menu-item')['default']
    ElSubmenu: typeof import('element-plus/es/el-submenu')['default']
    ElMenu: typeof import('element-plus/es/el-menu')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElOption: typeof import('element-plus/es/el-option')['default']
    ElSelect: typeof import('element-plus/es/el-select')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElDatePicker: typeof import('element-plus/es/el-date-picker')['default']
  }
}

export {}
